schemaVersion: 2.3.0
metadata:
  name: idzee-devspaces

components:
  - name: zowe
    volume:
      size: 100Mi
  - name: idzee-terminal
    container:
      image: jp.icr.io/phaumer/idzee-devspaces-sidecar@sha256:630f5ae2d7f2b627fc6a6b09bca03d9d0a7307fb01ccfb8ef2a4f078c8355dec
      memoryLimit: 3072Mi
      mountSources: true
      volumeMounts:
        - name: zowe
          path: /home/user/.zowe
