schemaVersion: 2.3.0
metadata:
  name: idzee-devspaces

components:
  - name: zowe
    volume:
      size: 100Mi
  - name: idzee-terminal
    container:
      # Multi-arch image test for full image
      # image: jp.icr.io/phaumer/idzee-devspaces:latest
      #  Multi-arch image test for base image
      image: jp.icr.io/phaumer/idzee-devspaces-udibase:5.3.1
      memoryLimit: 3072Mi
      mountSources: true
      volumeMounts:
        - name: zowe
          path: /home/user/.zowe
