schemaVersion: 2.3.0
metadata:
  name: wazi-udi

components:
  - name: zowe
    volume:
      size: 100Mi
  - name: wazi-terminal
    container:
      image: jp.icr.io/phaumer/ibm-wazi-for-devspaces-sidecar@sha256:8ee619327e6a4f0adc96cc399432b67e0b04ba6ceb6fd0e4cde156e7d06531a0
      memoryLimit: 3072Mi
      mountSources: true
      volumeMounts:
        - name: zowe
          path: /home/user/.zowe
