schemaVersion: 2.3.0
metadata:
  name: idzee-devspaces-udi-zowe

components:
  - name: zowe
    volume:
      size: 100Mi
  - name: udi-terminal
    container:
      image: registry.redhat.io/devspaces/udi-rhel8:3.16
      memoryLimit: 3072Mi
      mountSources: true
      volumeMounts:
        - name: zowe
          path: /home/user/.zowe
  - name: zowe-terminal
    container:
      image: jp.icr.io/phaumer/idzee-devspaces-sidecar-minimal:latest
      memoryLimit: 515Mi
      mountSources: true
      volumeMounts:
        - name: zowe
          path: /home/user/.zowe
