schemaVersion: 2.3.0
metadata:
  name: wazi-udi

components:
  - name: zowe
    volume:
      size: 100Mi
  - name: wazi-terminal
    container:
      image: stg.icr.io/phaumer/zopeneditor-sidcar@sha256:a041cbd9131eb462871f478b21e9b44abcf8fc42cc67f4efd022f6f23c9fbfcf
      memoryLimit: 3072Mi
      mountSources: true
      volumeMounts:
        - name: zowe
          path: /home/user/.zowe
