schemaVersion: 2.3.0
metadata:
  name: idzee-devspaces

components:
  - name: zowe
    volume:
      size: 100Mi
  - name: idzee-terminal
    container:
      image: jp.icr.io/phaumer/idzee-devspaces-sidecar@sha256:bf2d8095d23a87e90a52ede5c1da475425fc94a504a8083a3711ff2c50949819
      memoryLimit: 3072Mi
      mountSources: true
      volumeMounts:
        - name: zowe
          path: /home/user/.zowe
