###############################################################################
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corporation 2023. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
###############################################################################

vscode:
  extensions:
    - zowe.vscode-extension-for-zowe
    - ibm.zopeneditor
    - redhat.ansible
    - eamodio.gitlens

## Unsupported example image provided by the Wazi team
## Built using .gitpod.Dockerfile
image: quay.io/wazi/gitpod:latest

## Use if you want to generate the image in Gitpod
#image:
#  file: .gitpod.Dockerfile
